#language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t jokingarcia/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jokingarcia/docker-react npm run test